### ISSUE TITLE
excluded from hacktoberfest22

### ISSUE THREAD

**Issue by Shiyadh123** [abhijitmondal121/Hacktoberfest2022-profileCardGenerator#86]

**Comment by renzien** [comment]
Yea, because too many forks then the starred repo. I think

**Comment by Shiyadh123** [comment]
@abhijitmondal121  why dont u mention that this repo is excluded from hacktober22.
why u want to waste contributed time

**Comment by typhonshambo** [comment]
> Yea, because too many forks then the starred repo. I think

It's because this repo is not keeping the value of hacktoberfest, You can read their rules and guidelines
